services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./wait-for-it.sh:/wait-for-it.sh
    depends_on:
      - app
    entrypoint: ["/bin/sh", "-c", "chmod +x /wait-for-it.sh && /wait-for-it.sh app:3000 -- nginx -g 'daemon off;'"]

  app:
    build: ./app
    ports:
      - "3000:3000"
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: secret
      DB_NAME: people_db
    depends_on:
      - mysql
    entrypoint: ["/bin/sh", "-c", "chmod +x ./wait-for-it.sh && ./wait-for-it.sh mysql:3306 -- node index.js"]

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: people_db
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"

volumes:
  mysql_data: